Chord picker
4lejandrito/react-guitar pull request #27
Opened 2022-07-29 15:10 UTC by RyanButton

Hello there,

This PR contains implementation for the following tasks on [Issue #8](https://github.com/4lejandrito/react-guitar/issues/8):

- [ ]  Exclude impossible chord positions for 5 fingered humans
- [ ]  Shortcuts for common chords
- [ ]  More settings to filter the type of chords to show (bar chords, open strings...)

As well as this, I have added a story to the story book for testing the chord picker.

It's also worth noting that there are some issues within here that I believe are related to the core of the chord picker code, such as certain 'diminished triad' chords not being picked up.

The intention here is a first pass, then on acceptance `restrictChordTypeTo`, `getChordSemitones` etc can be expanded upon.

2022-07-29 21:41 UTC, 4lejandrito commented
Hi @RyanButton!

Thanks a lot for this!! I am super excited. However I'm a bit busy lately and it'll take me some time to go through it and your previous pull request. I'll let you know as soon as I have the time.

Thanks!

2022-08-07 21:22 UTC, 4lejandrito requested changes
Hi @RyanButton,

I made some initial comments. Also, I believe you included a package-lock json by accident. Are you using `npm` instead of `yarn`?

I'll review the logic in the next few days and let you know. 

Thanks!

2022-08-07 21:22 UTC, 4lejandrito commented on .vscode/settings.json
> +  "typescript.tsdk": "node_modules\\typescript\\lib"
I think you commited this file by accident.

2022-08-07 21:22 UTC, 4lejandrito commented on packages/react-guitar/src/styles/index.ts
> -/** @jsxRuntime classic /
I think you removed this by accident too.

2022-08-08 00:16 UTC, RyanButton commented
Thanks for the comments @4lejandrito. This PR needs a rebase to get newest changes from master (first PR you merged), and I also did mistakenly use npm instead of yarn (force of habit). Will fix her up in the next couple of days. Feel free to keep chugging along on reviewing the logic etc and will apply changes to that as well 🙂

2022-08-09 11:19 UTC, RyanButton commented
@4lejandrito I've rebased, removed the stray files, as well as squashed the commits. Feel free to review at your own leisure. Cheers 👍

2022-08-29 19:29 UTC, 4lejandrito commented
Hi @RyanButton,

I've come back to this. Would you mind adding a few tests to [fretter.test.ts](https://github.com/4lejandrito/react-guitar/blob/master/packages/react-guitar-fretter/src/__test__/fretter.test.ts)?

Also, if you're into React, what about surfacing this functionality to the UI? Somewhere in [this screen](https://github.com/4lejandrito/react-guitar/blob/master/site/components/ChordSelector.tsx): 

![Screenshot 2022-08-29 at 21-27-59 React Guitar](https://user-images.githubusercontent.com/1937354/187282478-7743bb82-29a5-4a73-896b-3bdcacf65796.png)

2022-08-30 17:17 UTC, 4lejandrito commented
Oh man congratulations!! I also had my first kid back in February, that's why it's taking me so long to review this 😅 . It's a wonderful experience, enjoy it, time flies.

2022-09-09 11:55 UTC, RyanButton commented
Hi @4lejandrito, implemented those suggestions. Fire at will 🙂

2022-10-23 21:21 UTC, 4lejandrito commented
Hi! I was testing this and found that the numbers don't really match... If you pick a C Major and pick "All" you get 19 possible chords, If you pick Open you get 2, and if you pick Barre you get 4... shouldn't Barre + Open = All?

2022-11-08 05:25 UTC, RyanButton commented
Disagree. I've defined open chords in-code as chords with at least one open string AND played within the first four frets (i.e the open position). I've then defined Barre chords as chords with at least two strings playing then same fret AND these frets cannot be an open fret AND they must be the minimum frets in the chord (closest to the neck). 

So for example, an F7 chord pictured below, in my opinion, is neither a barre chord or an open chord:
![image](https://user-images.githubusercontent.com/56656890/200481504-766e0cee-4ec0-4548-ae9b-c250a28fa8f9.png)

So in essence `Open chords ∪ Barre chords ≠ All chords` but `Open chords ∪ Barre chords ⊂ All chords`

Hope this helps 🙂

2026-05-18 14:35 UTC, 4lejandrito commented
I have to close this, sorry. I could not find the time to work on it, and it is probably irrelevant at this point. Thanks a lot!

2026-05-18 14:35 UTC, closed without merging